id: I426BB474
ocr_import_info:
  timestamp: '2023-09-29T09:08:09.781028+00:00'
  batch_id: batch-a70c
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: Dharma Kyab
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-09-29 09:27:04.391926+00:00
last_modified: 2023-09-29 09:27:04.391934+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W1NLM3530
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1NLM3530
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསང་སྤྱོད་སྙན་རྒྱུད་ལས་ཆུ་མིག་བརྒྱ་རྩ་སྒྲུབ་པའི་ཞལ་བཀོད་སོགས།
  languages:
  - bo
  author: གཤོངས་ཆེན་པ་བསྟན་པའི་རྒྱལ་མཚན།
statistics:
  ocr_word_mean_confidence_index: 0.8502857223140496
  ocr_word_median_confidence_index: 0.9204987
bases:
  I1NLM3530_001:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1NLM3530_001
      total_pages: 228
      volume_number: 1
      volume_pages_bdrc_intro: 0
    order: 1
    base_file: I1NLM3530_001.txt
    statistics:
      ocr_word_median_confidence_index: 0.9204987
      ocr_word_mean_confidence_index: 0.8502857223140496
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
